name: Format
on: push

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
      - name: format
        uses: JohnnyMorganz/stylua-action@76fd70c03e6340ceaf673366712db9b20560b402 # v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 2.1.0
          args: --check .
